name: Release

on:
  release:
    types: 
      - published
    branches:
      - master

jobs:
  build:
    name: Build
    uses: PetrBilek1/Portfolio/.github/workflows/build.yml@master
    secrets: inherit
  
  publish:
    needs: build
    name: Publish
    permissions:
      contents: read
      packages: write
    uses: PetrBilek1/Portfolio/.github/workflows/publish-ghcr.yml@master
    secrets: inherit
